"use client";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen">
          <div className="flex flex-grow">
            <div className="flex flex-col flex-grow ">
              <div
                className="flex-grow p-4 "
                style={{
                  background: "#f5f5f5",
                }}
              >
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
